server:
  port: 8888

spring:
  application:
    name: x_cinema

  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: root123
    url: jdbc:postgresql://localhost:5432/x_cinema

    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      connection-timeout: 5000
      idle-timeout: 300000
      pool-name: HikariPool

    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: on

logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.hibernate.engine.jdbc.connections: DEBUG
